### ISSUE TITLE
Assertion failed: (handle->InternalFieldCount() > 0)

### ISSUE THREAD

**Issue by skaren** [mechio/takana#66]
At the start of Takana I get the following error:

```
Assertion failed: (handle->InternalFieldCount() > 0), function Wrap, file /Users/anonymous/.node-gyp/0.12.0/src/node_object_wrap.h, line 77.
```

This is the verbose logging:

```
[2015-02-11 23:00:27.739] [DEBUG] Server - Staring...
[2015-02-11 23:00:27.739] [DEBUG] Server - starting rsync
[2015-02-11 23:00:27.745] [INFO] EditorManager - editor server listening on 48627
[2015-02-11 23:00:27.746] [INFO] Server - webserver listening on 48626
[2015-02-11 23:00:27.754] [DEBUG] Server - rsync finished
Assertion failed: (handle->InternalFieldCount() > 0), function Wrap, file /Users/anonymous/.node-gyp/0.12.0/src/node_object_wrap.h, line 77.
Abort trap: 6
```

**Comment by clarkewd** [comment]
after upgrading node with homebrew I'm now getting this error, too, and can't get `takana` to start - with any version ( e.g. `takana@0.4.2` or `takana@0.2.1` )

**Comment by zacherybcampbell** [comment]
I'm having the same issue.

**Comment by clarkewd** [comment]
I was able to get takana working again, temporarily, by rolling back to an older version of node - v0.10.36 worked while v0.12 seemed to cause this issue.

**Comment by foolscreen** [comment]
Seems that the problem exists only in OS X 10.9, i am having the same issue on my colleagues iMac but having no problems on my MacBook with 10.10 
both Systems say:
npm version
{ npm: '2.6.0',
  http_parser: '2.3',
  modules: '14',
  node: '0.12.0',
  openssl: '1.0.1l',
  uv: '1.0.2',
  v8: '3.28.73',
  zlib: '1.2.8' }

Is there any solution in the near future? Switching back to older versions doesn't seem to work in our case.

**Comment by tsujp** [comment]
I'm currently on 10.10.2 using Node v0.12.0 with the latest version of Takana 0.4.2 and I get the same error. I tried rolling back to Node v0.10.36 and that didn't work either.

Thus far Takana isn't useable as it sits right now on this setup.

**Comment by dprovost1990** [comment]
Same problem here on yosemite osx.  Uninstalling node via brew (as that is how it was installed).  Going to install node v.0.10.36 as described in this tutorial: http://www.websector.de/blog/2011/12/15/quick-tip-node-how-to-downgrade-node-js-on-os-x/

**Comment by dprovost1990** [comment]
update:  downgrading node as described above worked. So its working on yosemite 10.10.2 this way...

**Comment by timdmackey** [comment]
I tried the instructions above to downgrade node, but that just resulted in new and different error messages when I tried to run takana:

    dyld: lazy symbol binding failed: Symbol not found: _node_module_register
      Referenced from: /usr/local/lib/node_modules/takana/node_modules/websocket/build/Release/bufferutil.node
      Expected in: dynamic lookup

    dyld: Symbol not found: _node_module_register
      Referenced from: /usr/local/lib/node_modules/takana/node_modules/websocket/build/Release/bufferutil.node
      Expected in: dynamic lookup

I probably just did something wrong, any ideas?

It would be nice to get this fixed so we can just use the current version of Node.

**Comment by timdmackey** [comment]
Has anyone made any progress with this?

**Comment by MatthewKosloski** [comment]
I get the same problem on OSX 10.9.4
![screen shot 2015-03-21 at 9 21 52 pm](https://cloud.githubusercontent.com/assets/1219553/6767726/5f1b0e56-d010-11e4-8fd7-6f05901fe938.png)

**Comment by rrrrrraul** [comment]
I'm running OSX 10.10.2, I downgraded to node v0.10.36 from v0.12 and it now gets passed "Assertion failed .." 

However, now it stops with: "Segmentation fault : 11"

**Comment by barnaby** [comment]
fixed in `0.4.3`
